<?php
$config=array(
    'root_path'=>'/var/www/html/delionir',
    'dir'=>'/delionir/control_panel/',
    'url'=>'http://localhost/delionir/',
    'host'=>'localhost',
    'user'=>'root',
    'password'=>'1815',
    'database'=>'delionir'
);
?>